// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/bosh-backup-and-restore/instance"
	"github.com/cloudfoundry-incubator/bosh-backup-and-restore/orchestrator"
	"github.com/cloudfoundry-incubator/bosh-backup-and-restore/ssh"
)

type FakeJobFinder struct {
	FindJobsStub        func(instance.InstanceIdentifier, ssh.RemoteRunner, instance.ManifestQuerier) (orchestrator.Jobs, error)
	findJobsMutex       sync.RWMutex
	findJobsArgsForCall []struct {
		arg1 instance.InstanceIdentifier
		arg2 ssh.RemoteRunner
		arg3 instance.ManifestQuerier
	}
	findJobsReturns struct {
		result1 orchestrator.Jobs
		result2 error
	}
	findJobsReturnsOnCall map[int]struct {
		result1 orchestrator.Jobs
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeJobFinder) FindJobs(arg1 instance.InstanceIdentifier, arg2 ssh.RemoteRunner, arg3 instance.ManifestQuerier) (orchestrator.Jobs, error) {
	fake.findJobsMutex.Lock()
	ret, specificReturn := fake.findJobsReturnsOnCall[len(fake.findJobsArgsForCall)]
	fake.findJobsArgsForCall = append(fake.findJobsArgsForCall, struct {
		arg1 instance.InstanceIdentifier
		arg2 ssh.RemoteRunner
		arg3 instance.ManifestQuerier
	}{arg1, arg2, arg3})
	stub := fake.FindJobsStub
	fakeReturns := fake.findJobsReturns
	fake.recordInvocation("FindJobs", []interface{}{arg1, arg2, arg3})
	fake.findJobsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeJobFinder) FindJobsCallCount() int {
	fake.findJobsMutex.RLock()
	defer fake.findJobsMutex.RUnlock()
	return len(fake.findJobsArgsForCall)
}

func (fake *FakeJobFinder) FindJobsCalls(stub func(instance.InstanceIdentifier, ssh.RemoteRunner, instance.ManifestQuerier) (orchestrator.Jobs, error)) {
	fake.findJobsMutex.Lock()
	defer fake.findJobsMutex.Unlock()
	fake.FindJobsStub = stub
}

func (fake *FakeJobFinder) FindJobsArgsForCall(i int) (instance.InstanceIdentifier, ssh.RemoteRunner, instance.ManifestQuerier) {
	fake.findJobsMutex.RLock()
	defer fake.findJobsMutex.RUnlock()
	argsForCall := fake.findJobsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeJobFinder) FindJobsReturns(result1 orchestrator.Jobs, result2 error) {
	fake.findJobsMutex.Lock()
	defer fake.findJobsMutex.Unlock()
	fake.FindJobsStub = nil
	fake.findJobsReturns = struct {
		result1 orchestrator.Jobs
		result2 error
	}{result1, result2}
}

func (fake *FakeJobFinder) FindJobsReturnsOnCall(i int, result1 orchestrator.Jobs, result2 error) {
	fake.findJobsMutex.Lock()
	defer fake.findJobsMutex.Unlock()
	fake.FindJobsStub = nil
	if fake.findJobsReturnsOnCall == nil {
		fake.findJobsReturnsOnCall = make(map[int]struct {
			result1 orchestrator.Jobs
			result2 error
		})
	}
	fake.findJobsReturnsOnCall[i] = struct {
		result1 orchestrator.Jobs
		result2 error
	}{result1, result2}
}

func (fake *FakeJobFinder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.findJobsMutex.RLock()
	defer fake.findJobsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeJobFinder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ instance.JobFinder = new(FakeJobFinder)
