// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/bosh-backup-and-restore/instance"
)

type FakeReleaseMappingFinder struct {
	Stub        func(manifest string, instanceNames []string) instance.ReleaseMapping
	mutex       sync.RWMutex
	argsForCall []struct {
		manifest      string
		instanceNames []string
	}
	returns struct {
		result1 instance.ReleaseMapping
	}
	returnsOnCall map[int]struct {
		result1 instance.ReleaseMapping
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeReleaseMappingFinder) Spy(manifest string, instanceNames []string) instance.ReleaseMapping {
	var instanceNamesCopy []string
	if instanceNames != nil {
		instanceNamesCopy = make([]string, len(instanceNames))
		copy(instanceNamesCopy, instanceNames)
	}
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		manifest      string
		instanceNames []string
	}{manifest, instanceNamesCopy})
	fake.recordInvocation("ReleaseMappingFinder", []interface{}{manifest, instanceNamesCopy})
	fake.mutex.Unlock()
	if fake.Stub != nil {
		return fake.Stub(manifest, instanceNames)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.returns.result1
}

func (fake *FakeReleaseMappingFinder) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeReleaseMappingFinder) ArgsForCall(i int) (string, []string) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].manifest, fake.argsForCall[i].instanceNames
}

func (fake *FakeReleaseMappingFinder) Returns(result1 instance.ReleaseMapping) {
	fake.Stub = nil
	fake.returns = struct {
		result1 instance.ReleaseMapping
	}{result1}
}

func (fake *FakeReleaseMappingFinder) ReturnsOnCall(i int, result1 instance.ReleaseMapping) {
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 instance.ReleaseMapping
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 instance.ReleaseMapping
	}{result1}
}

func (fake *FakeReleaseMappingFinder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeReleaseMappingFinder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ instance.ReleaseMappingFinder = new(FakeReleaseMappingFinder).Spy
