---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfplatformrecovery/backup-and-restore-minimal

inputs:
- name: bosh-backup-and-restore

params:
  AWS_SECRET_KEY:
  AWS_ACCESS_KEY:
  AWS_ASSUMED_ROLE_ARN:

run:
  path: bosh-backup-and-restore/ci/tasks/bbr-s3-config-validator-e2e-test/task.sh
