---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
  - name: bosh-backup-and-restore-ci
  - name: bosh-deployment
  - name: bosh-bootloader

outputs:
  - name: bbl-state

params:
  BBL_GCP_SERVICE_ACCOUNT_KEY: ((gcp_json_key))
  BBL_IAAS: gcp
  BBL_GCP_REGION: europe-west1
  PIPELINE_JOB: ~
  WARDEN_CONTAINERS_USE_SYSTEMD: true
  DISABLE_HM_RESURRECTOR: false

run:
  path: bosh-backup-and-restore-ci/ci/tasks/bbl-up/task.sh
