version: '3'

services:
  dind:
    image: docker:dind
    privileged: yes
    environment:
    - DOCKER_TLS_CERTDIR=
    - DOCKER_HOST=
    healthcheck:
      test: 'docker ps'
      start_period: 1m
      retries: 20

  bbr-unit:
    depends_on:
      dind:
        condition: service_healthy
    build: { context: ., dockerfile: ci/dockerfiles/bbr-unit/Dockerfile }
    entrypoint: "make test"
    environment:
    - DOCKER_HOST=tcp://dind:2375
