---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang-image

inputs:
- name: bosh-backup-and-restore

run:
  path: bosh-backup-and-restore/ci/tasks/test-unit/task.sh
