// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/bosh-backup-and-restore/orchestrator"
)

type FakeDeploymentManager struct {
	FindStub        func(string) (orchestrator.Deployment, error)
	findMutex       sync.RWMutex
	findArgsForCall []struct {
		arg1 string
	}
	findReturns struct {
		result1 orchestrator.Deployment
		result2 error
	}
	findReturnsOnCall map[int]struct {
		result1 orchestrator.Deployment
		result2 error
	}
	SaveManifestStub        func(string, orchestrator.Backup) error
	saveManifestMutex       sync.RWMutex
	saveManifestArgsForCall []struct {
		arg1 string
		arg2 orchestrator.Backup
	}
	saveManifestReturns struct {
		result1 error
	}
	saveManifestReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDeploymentManager) Find(arg1 string) (orchestrator.Deployment, error) {
	fake.findMutex.Lock()
	ret, specificReturn := fake.findReturnsOnCall[len(fake.findArgsForCall)]
	fake.findArgsForCall = append(fake.findArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Find", []interface{}{arg1})
	fake.findMutex.Unlock()
	if fake.FindStub != nil {
		return fake.FindStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.findReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDeploymentManager) FindCallCount() int {
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	return len(fake.findArgsForCall)
}

func (fake *FakeDeploymentManager) FindCalls(stub func(string) (orchestrator.Deployment, error)) {
	fake.findMutex.Lock()
	defer fake.findMutex.Unlock()
	fake.FindStub = stub
}

func (fake *FakeDeploymentManager) FindArgsForCall(i int) string {
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	argsForCall := fake.findArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDeploymentManager) FindReturns(result1 orchestrator.Deployment, result2 error) {
	fake.findMutex.Lock()
	defer fake.findMutex.Unlock()
	fake.FindStub = nil
	fake.findReturns = struct {
		result1 orchestrator.Deployment
		result2 error
	}{result1, result2}
}

func (fake *FakeDeploymentManager) FindReturnsOnCall(i int, result1 orchestrator.Deployment, result2 error) {
	fake.findMutex.Lock()
	defer fake.findMutex.Unlock()
	fake.FindStub = nil
	if fake.findReturnsOnCall == nil {
		fake.findReturnsOnCall = make(map[int]struct {
			result1 orchestrator.Deployment
			result2 error
		})
	}
	fake.findReturnsOnCall[i] = struct {
		result1 orchestrator.Deployment
		result2 error
	}{result1, result2}
}

func (fake *FakeDeploymentManager) SaveManifest(arg1 string, arg2 orchestrator.Backup) error {
	fake.saveManifestMutex.Lock()
	ret, specificReturn := fake.saveManifestReturnsOnCall[len(fake.saveManifestArgsForCall)]
	fake.saveManifestArgsForCall = append(fake.saveManifestArgsForCall, struct {
		arg1 string
		arg2 orchestrator.Backup
	}{arg1, arg2})
	fake.recordInvocation("SaveManifest", []interface{}{arg1, arg2})
	fake.saveManifestMutex.Unlock()
	if fake.SaveManifestStub != nil {
		return fake.SaveManifestStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.saveManifestReturns
	return fakeReturns.result1
}

func (fake *FakeDeploymentManager) SaveManifestCallCount() int {
	fake.saveManifestMutex.RLock()
	defer fake.saveManifestMutex.RUnlock()
	return len(fake.saveManifestArgsForCall)
}

func (fake *FakeDeploymentManager) SaveManifestCalls(stub func(string, orchestrator.Backup) error) {
	fake.saveManifestMutex.Lock()
	defer fake.saveManifestMutex.Unlock()
	fake.SaveManifestStub = stub
}

func (fake *FakeDeploymentManager) SaveManifestArgsForCall(i int) (string, orchestrator.Backup) {
	fake.saveManifestMutex.RLock()
	defer fake.saveManifestMutex.RUnlock()
	argsForCall := fake.saveManifestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeDeploymentManager) SaveManifestReturns(result1 error) {
	fake.saveManifestMutex.Lock()
	defer fake.saveManifestMutex.Unlock()
	fake.SaveManifestStub = nil
	fake.saveManifestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDeploymentManager) SaveManifestReturnsOnCall(i int, result1 error) {
	fake.saveManifestMutex.Lock()
	defer fake.saveManifestMutex.Unlock()
	fake.SaveManifestStub = nil
	if fake.saveManifestReturnsOnCall == nil {
		fake.saveManifestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveManifestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDeploymentManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	fake.saveManifestMutex.RLock()
	defer fake.saveManifestMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDeploymentManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ orchestrator.DeploymentManager = new(FakeDeploymentManager)
