// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-backup-and-restore/orchestrator"
)

type FakeBackupManager struct {
	CreateStub        func(string, string, orchestrator.Logger) (orchestrator.Backup, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 orchestrator.Logger
	}
	createReturns struct {
		result1 orchestrator.Backup
		result2 error
	}
	createReturnsOnCall map[int]struct {
		result1 orchestrator.Backup
		result2 error
	}
	OpenStub        func(string, orchestrator.Logger) (orchestrator.Backup, error)
	openMutex       sync.RWMutex
	openArgsForCall []struct {
		arg1 string
		arg2 orchestrator.Logger
	}
	openReturns struct {
		result1 orchestrator.Backup
		result2 error
	}
	openReturnsOnCall map[int]struct {
		result1 orchestrator.Backup
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBackupManager) Create(arg1 string, arg2 string, arg3 orchestrator.Logger) (orchestrator.Backup, error) {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 orchestrator.Logger
	}{arg1, arg2, arg3})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2, arg3})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBackupManager) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeBackupManager) CreateCalls(stub func(string, string, orchestrator.Logger) (orchestrator.Backup, error)) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeBackupManager) CreateArgsForCall(i int) (string, string, orchestrator.Logger) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBackupManager) CreateReturns(result1 orchestrator.Backup, result2 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 orchestrator.Backup
		result2 error
	}{result1, result2}
}

func (fake *FakeBackupManager) CreateReturnsOnCall(i int, result1 orchestrator.Backup, result2 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 orchestrator.Backup
			result2 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 orchestrator.Backup
		result2 error
	}{result1, result2}
}

func (fake *FakeBackupManager) Open(arg1 string, arg2 orchestrator.Logger) (orchestrator.Backup, error) {
	fake.openMutex.Lock()
	ret, specificReturn := fake.openReturnsOnCall[len(fake.openArgsForCall)]
	fake.openArgsForCall = append(fake.openArgsForCall, struct {
		arg1 string
		arg2 orchestrator.Logger
	}{arg1, arg2})
	stub := fake.OpenStub
	fakeReturns := fake.openReturns
	fake.recordInvocation("Open", []interface{}{arg1, arg2})
	fake.openMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBackupManager) OpenCallCount() int {
	fake.openMutex.RLock()
	defer fake.openMutex.RUnlock()
	return len(fake.openArgsForCall)
}

func (fake *FakeBackupManager) OpenCalls(stub func(string, orchestrator.Logger) (orchestrator.Backup, error)) {
	fake.openMutex.Lock()
	defer fake.openMutex.Unlock()
	fake.OpenStub = stub
}

func (fake *FakeBackupManager) OpenArgsForCall(i int) (string, orchestrator.Logger) {
	fake.openMutex.RLock()
	defer fake.openMutex.RUnlock()
	argsForCall := fake.openArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBackupManager) OpenReturns(result1 orchestrator.Backup, result2 error) {
	fake.openMutex.Lock()
	defer fake.openMutex.Unlock()
	fake.OpenStub = nil
	fake.openReturns = struct {
		result1 orchestrator.Backup
		result2 error
	}{result1, result2}
}

func (fake *FakeBackupManager) OpenReturnsOnCall(i int, result1 orchestrator.Backup, result2 error) {
	fake.openMutex.Lock()
	defer fake.openMutex.Unlock()
	fake.OpenStub = nil
	if fake.openReturnsOnCall == nil {
		fake.openReturnsOnCall = make(map[int]struct {
			result1 orchestrator.Backup
			result2 error
		})
	}
	fake.openReturnsOnCall[i] = struct {
		result1 orchestrator.Backup
		result2 error
	}{result1, result2}
}

func (fake *FakeBackupManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	fake.openMutex.RLock()
	defer fake.openMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBackupManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ orchestrator.BackupManager = new(FakeBackupManager)
