---
resource_types:
- name: build-metadata
  type: registry-image
  source:
    repository: pcfopsmanager/build-metadata-resource

resources:
- name: release-candidate-version
  type: semver
  icon: google
  source:
    bucket: release-versions
    key: bosh-backup-and-restore/release-candidate
    json_key: ((gcp/service_accounts/bucket_owner.json_key))
    initial_version: 1.9.13-rc.1
    driver: gcs
- name: main
  icon: github
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh-backup-and-restore.git
    private_key: ((github.ssh_key))
    branch: master
    disable_git_lfs: true
- name: srp-helper
  type: registry-image
  source:
    repository: harbor.dhaka.cf-app.com/srp/srp-helper-task # synced periodically from internal artifactory
    username: ((srp-helper-harbor-credentials.username))
    password: ((srp-helper-harbor-credentials.password))
- name: build-metadata
  type: build-metadata

jobs:
# https://confluence.eng.vmware.com/pages/viewpage.action?pageId=1391547014
- name: collect-source-provenance
  plan:
  - get: srp-helper
  - get: main
    trigger: true
  - get: release-candidate-version
  - get: build-metadata
  - task: submit-metadata
    image: srp-helper
    config:
      platform: linux
      inputs:
      - name: main
      - name: build-metadata
      - name: release-candidate-version
      run:
        path: /bin/bash
        args:
        - -c
        - |
          set -euo pipefail

          mkdir ./provenance
          
          VERSION=$(cat release-candidate-version/version)
          BUILD_NUMBER=$(cat build-metadata/build-name)
          BUILD_PIPELINE_NAME=$(cat build-metadata/build-pipeline-name)
          BUILD_JOB_NAME=$(cat build-metadata/build-job-name)
          BUILD_ID=$(cat build-metadata/build-id)

          COMP_UID="uid.obj.build.concourse(instance='cryogenics',namespace='bosh-addons',pipeline='$BUILD_PIPELINE_NAME',job='$BUILD_JOB_NAME',build_id='$BUILD_ID')"

          srp --version

          srp provenance source \
            --scm-type git \
            --name "p-bosh-backup-and-restore" \
            --path main/ \
            --saveto ./provenance/source.json \
            --build-number "$BUILD_NUMBER" \
            --version "$VERSION" \
            --all-ephemeral true \
            --build-type release \
            --comp-uid "$COMP_UID"

          srp config auth \
            --client-id $SRP_CLIENT_ID \
            --client-secret $SRP_CLIENT_SECRET \
            --url $SRP_URL \
            --verbose

          srp metadata status \
            --url $SRP_URL

          srp metadata submit \
            -p ./provenance/source.json \
            -u "uid.mtd.provenance_2_5.fragment(obj_uid=$COMP_UID)" \
            --url $SRP_URL

          srp metadata get \
            --schema provenance \
            --version v2.5f \
            --pretty \
            --url $SRP_URL \
            --uid "uid.mtd.provenance_2_5.fragment(obj_uid=$COMP_UID)"

      params:
        SRP_CLIENT_ID: ((srp-integration-vcs-client.clientId))
        SRP_CLIENT_SECRET: ((srp-integration-vcs-client.clientSecret))
        SRP_URL: https://apigw.vmware.com/v1/s1/api/helix-beta

