---
platform: linux

image_resource:
  type: registry-image
  source: {repository: pcfplatformrecovery/backup-and-restore}

inputs:
- name: version
- name: bbr-build
- name: bbr-s3-config-validator-build
- name: bosh-backup-and-restore-ci

outputs:
- name: packaged-release
- name: release_metadata

run:
  path: bosh-backup-and-restore-ci/ci/tasks/package-release/task.sh
