---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfplatformrecovery/backup-and-restore-minimal

inputs:
- name: bosh-backup-and-restore
- name: version
  optional: true

outputs:
- name: bbr-s3-config-validator-build

run:
  path: bosh-backup-and-restore/ci/tasks/bbr-s3-config-validator-build/task.sh
