platform: linux
inputs:
  - name: bosh-backup-and-restore-ci
  - name: integration-configs
  - name: cf-deployment-env
outputs:
  - name: updated-integration-configs
params:
  CF_DEPLOYMENT_NAME: cf
  INTEGRATION_CONFIG_FILE_PATH: ci/integration_config.json
  SYSTEM_DOMAIN:
  CREDHUB_CLIENT: ""
  CREDHUB_SECRET: ""
run:
  path: bosh-backup-and-restore-ci/ci/tasks/setup-drats-integration-config/task.sh
