// This file was generated by counterfeiter
package fakes

import (
	"io"
	"sync"

	"github.com/pivotal-cf/pcf-backup-and-restore/bosh"
)

type FakeSSHConnection struct {
	StreamStub        func(cmd string, writer io.Writer) ([]byte, int, error)
	streamMutex       sync.RWMutex
	streamArgsForCall []struct {
		cmd    string
		writer io.Writer
	}
	streamReturns struct {
		result1 []byte
		result2 int
		result3 error
	}
	StreamStdinStub        func(cmd string, reader io.Reader) ([]byte, []byte, int, error)
	streamStdinMutex       sync.RWMutex
	streamStdinArgsForCall []struct {
		cmd    string
		reader io.Reader
	}
	streamStdinReturns struct {
		result1 []byte
		result2 []byte
		result3 int
		result4 error
	}
	RunStub        func(cmd string) ([]byte, []byte, int, error)
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		cmd string
	}
	runReturns struct {
		result1 []byte
		result2 []byte
		result3 int
		result4 error
	}
	CleanupStub        func() error
	cleanupMutex       sync.RWMutex
	cleanupArgsForCall []struct{}
	cleanupReturns     struct {
		result1 error
	}
	UsernameStub        func() string
	usernameMutex       sync.RWMutex
	usernameArgsForCall []struct{}
	usernameReturns     struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSSHConnection) Stream(cmd string, writer io.Writer) ([]byte, int, error) {
	fake.streamMutex.Lock()
	fake.streamArgsForCall = append(fake.streamArgsForCall, struct {
		cmd    string
		writer io.Writer
	}{cmd, writer})
	fake.recordInvocation("Stream", []interface{}{cmd, writer})
	fake.streamMutex.Unlock()
	if fake.StreamStub != nil {
		return fake.StreamStub(cmd, writer)
	} else {
		return fake.streamReturns.result1, fake.streamReturns.result2, fake.streamReturns.result3
	}
}

func (fake *FakeSSHConnection) StreamCallCount() int {
	fake.streamMutex.RLock()
	defer fake.streamMutex.RUnlock()
	return len(fake.streamArgsForCall)
}

func (fake *FakeSSHConnection) StreamArgsForCall(i int) (string, io.Writer) {
	fake.streamMutex.RLock()
	defer fake.streamMutex.RUnlock()
	return fake.streamArgsForCall[i].cmd, fake.streamArgsForCall[i].writer
}

func (fake *FakeSSHConnection) StreamReturns(result1 []byte, result2 int, result3 error) {
	fake.StreamStub = nil
	fake.streamReturns = struct {
		result1 []byte
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeSSHConnection) StreamStdin(cmd string, reader io.Reader) ([]byte, []byte, int, error) {
	fake.streamStdinMutex.Lock()
	fake.streamStdinArgsForCall = append(fake.streamStdinArgsForCall, struct {
		cmd    string
		reader io.Reader
	}{cmd, reader})
	fake.recordInvocation("StreamStdin", []interface{}{cmd, reader})
	fake.streamStdinMutex.Unlock()
	if fake.StreamStdinStub != nil {
		return fake.StreamStdinStub(cmd, reader)
	} else {
		return fake.streamStdinReturns.result1, fake.streamStdinReturns.result2, fake.streamStdinReturns.result3, fake.streamStdinReturns.result4
	}
}

func (fake *FakeSSHConnection) StreamStdinCallCount() int {
	fake.streamStdinMutex.RLock()
	defer fake.streamStdinMutex.RUnlock()
	return len(fake.streamStdinArgsForCall)
}

func (fake *FakeSSHConnection) StreamStdinArgsForCall(i int) (string, io.Reader) {
	fake.streamStdinMutex.RLock()
	defer fake.streamStdinMutex.RUnlock()
	return fake.streamStdinArgsForCall[i].cmd, fake.streamStdinArgsForCall[i].reader
}

func (fake *FakeSSHConnection) StreamStdinReturns(result1 []byte, result2 []byte, result3 int, result4 error) {
	fake.StreamStdinStub = nil
	fake.streamStdinReturns = struct {
		result1 []byte
		result2 []byte
		result3 int
		result4 error
	}{result1, result2, result3, result4}
}

func (fake *FakeSSHConnection) Run(cmd string) ([]byte, []byte, int, error) {
	fake.runMutex.Lock()
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		cmd string
	}{cmd})
	fake.recordInvocation("Run", []interface{}{cmd})
	fake.runMutex.Unlock()
	if fake.RunStub != nil {
		return fake.RunStub(cmd)
	} else {
		return fake.runReturns.result1, fake.runReturns.result2, fake.runReturns.result3, fake.runReturns.result4
	}
}

func (fake *FakeSSHConnection) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeSSHConnection) RunArgsForCall(i int) string {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return fake.runArgsForCall[i].cmd
}

func (fake *FakeSSHConnection) RunReturns(result1 []byte, result2 []byte, result3 int, result4 error) {
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 []byte
		result2 []byte
		result3 int
		result4 error
	}{result1, result2, result3, result4}
}

func (fake *FakeSSHConnection) Cleanup() error {
	fake.cleanupMutex.Lock()
	fake.cleanupArgsForCall = append(fake.cleanupArgsForCall, struct{}{})
	fake.recordInvocation("Cleanup", []interface{}{})
	fake.cleanupMutex.Unlock()
	if fake.CleanupStub != nil {
		return fake.CleanupStub()
	} else {
		return fake.cleanupReturns.result1
	}
}

func (fake *FakeSSHConnection) CleanupCallCount() int {
	fake.cleanupMutex.RLock()
	defer fake.cleanupMutex.RUnlock()
	return len(fake.cleanupArgsForCall)
}

func (fake *FakeSSHConnection) CleanupReturns(result1 error) {
	fake.CleanupStub = nil
	fake.cleanupReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSSHConnection) Username() string {
	fake.usernameMutex.Lock()
	fake.usernameArgsForCall = append(fake.usernameArgsForCall, struct{}{})
	fake.recordInvocation("Username", []interface{}{})
	fake.usernameMutex.Unlock()
	if fake.UsernameStub != nil {
		return fake.UsernameStub()
	} else {
		return fake.usernameReturns.result1
	}
}

func (fake *FakeSSHConnection) UsernameCallCount() int {
	fake.usernameMutex.RLock()
	defer fake.usernameMutex.RUnlock()
	return len(fake.usernameArgsForCall)
}

func (fake *FakeSSHConnection) UsernameReturns(result1 string) {
	fake.UsernameStub = nil
	fake.usernameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeSSHConnection) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.streamMutex.RLock()
	defer fake.streamMutex.RUnlock()
	fake.streamStdinMutex.RLock()
	defer fake.streamStdinMutex.RUnlock()
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	fake.cleanupMutex.RLock()
	defer fake.cleanupMutex.RUnlock()
	fake.usernameMutex.RLock()
	defer fake.usernameMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeSSHConnection) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ bosh.SSHConnection = new(FakeSSHConnection)
